config/routes.rb
Rails.application.routes.draw do

 root 'pages#landing_page'

 get '/druga' => 'pages#druga'

 get '/treca' => 'pages#treca'

 get '/cetvrta' => 'pages#cetvrta'

 get '/peta' => 'pages#peta'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def landing_page

    end 


    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<!--Footer-->
<footer class="page-footer font-small indigo pt-0">

    <!--Footer Links-->
    <div class="container">

        <!--First row-->
        <div class="row">

            <!--First column-->
            <div class="col-md-12 py-5">

                <div class="mb-5 flex-center">
<center>
                    <img class="footer_icons" src="/fbicon.png" />
                    <img class="footer_icons" src="/instaicon.png" />
                    <img class="footer_icons" src="/twittericon.jpg" />
                    <img class="footer_icons" src="/youtubeicon.jpg" />
</center>

                </div>
            </div>
            <!--/First column-->
        </div>
        <!--/First row-->
    </div>
    <!--/Footer Links-->

    <!--Copyright-->
    <div class="footer-copyright py-3 text-center">
        © 2018 Copyright: Amina & Fatima
    </div>
    <!--/Copyright-->

</footer>
<!--/Footer-->

<style>
.footer_icons{
    width: 50px;
    height: 50px;
    margin: 30px;   
}

</style>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">WeddingDay</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="<%= druga_path %>">O nama</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= treca_path %>">Katalog</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= cetvrta_path %>">Lokacija</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= peta_path %>">Login</a>
      </li>
      

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeddingDay</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
   
  </head>

  <body>
  <center> <h1 style="font-family:Edwardian Script ITC; font-size:600%;"d> W e d d i n g  D a y </h1> </center>
  <%= render 'layouts/navbar' %>
  <br/>
  <div class="container">
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/pages/cetvrta.html.erb
<div class="row">
<div class="col-md-2">
  <img src="/slika23.jpg" style="width:120% ; height: 80%">
</div>
<div class="col-md-2">
  <img src="/slika28.jpg" style="width:120% ; height: 80%">
</div>
<div class="col-md-2">
  <img src="/slika30.jpg" style="width:120% ; height: 80%">
</div>
<div class="col-md-2">
  <img src="/slika22.jpg" style="width:120% ; height: 80%">
</div>
<div class="col-md-2">
  <img src="/slika31.jpg" style="width:120% ; height: 80%">
</div>
<div class="col-md-2">
  <img src="/slika24.jpg" style="width:120% ; height: 80%">
</div>
</div>

<br> </br>


<h1 style="font-family:Edwardian Script ITC; font-size:500%;"> L o k a c i j a . . . </h1> 

<br> </br>



<p style= "font-size:120%;"> Wedding day agencija za organizaciju vjenčanja je locirana u Sarajevu. Objekat se nalazi u ulici Trg djece Sarajeva 1, tačnije u centru BBI. <br>  Unutar objekta od 100m2 nalaze se dvije visokokvalitetne i opremljene kancelarije, dok je skladište, takođe locirano u Sarajevu, nedaleko od glavnog objekta u ulici Dubrovačka. </p>






<br> </br>


<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}

#myImg {
    border-radius: 5px;
    cursor: pointer;
    transition: 0.3s;
}

#myImg:hover {opacity: 0.7;}

/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.9); /* Black w/ opacity */
}

/* Modal Content (image) */
.modal-content {
    margin: auto;
    display: block;
    width: 100%;
    max-width: 900px;
}

/* Caption of Modal Image */
#caption {
    margin: auto;
    display: block;
    width: 80%;
    max-width: 700px;
    text-align: center;
    color: #ccc;
    padding: 10px 0;
    height: 150px;
}

/* Add Animation */
.modal-content, #caption {    
    -webkit-animation-name: zoom;
    -webkit-animation-duration: 0.6s;
    animation-name: zoom;
    animation-duration: 0.6s;
}

@-webkit-keyframes zoom {
    from {-webkit-transform:scale(0)} 
    to {-webkit-transform:scale(1)}
}

@keyframes zoom {
    from {transform:scale(0)} 
    to {transform:scale(1)}
}

/* The Close Button */
.close {
    position: absolute;
    top: 15px;
    right: 35px;
    color: #f1f1f1;
    font-size: 40px;
    font-weight: bold;
    transition: 0.3s;
}

.close:hover,
.close:focus {
    color: #bbb;
    text-decoration: none;
    cursor: pointer;
}

/* 100% Image Width on Smaller Screens */
@media only screen and (max-width: 700px){
    .modal-content {
        width: 100%;
    }
}


</style>
</head>
<body>



<div class= "row">

<div class="col-md-6">
  <img id="myImg" src="/lokacija1.jpg" alt="Lokacija" width="550" height="300">
 
  </div>
 


<!-- The Modal -->
<div id="myModal" class="modal">
  <span class="close">&times;</span>
  <img class="modal-content" id="img01">
  <div id="caption"></div>
</div>

<script>
// Get the modal
var modal = document.getElementById('myModal');

// Get the image and insert it inside the modal - use its "alt" text as a caption
var img = document.getElementById('myImg');
var modalImg = document.getElementById("img01");
var captionText = document.getElementById("caption");
img.onclick = function(){
    modal.style.display = "block";
    modalImg.src = this.src;
    captionText.innerHTML = this.alt;
}

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks on <span> (x), close the modal
span.onclick = function() { 
    modal.style.display = "none";
}
</script>

</body>
</html>










<br> </br>
<br> </br>
<br> </br>
<br> </br>





<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}

input[type=text], select, textarea {
    width: 100%;
    padding: 12px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    margin-top: 6px;
    margin-bottom: 16px;
    resize: vertical;
}

input[type=submit] {
    
    color: white;
    padding: 12px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}

input[type=submit]:hover {
    
}

.container {
    border-radius: 5px;
   
    
    padding: 20px;
}
</style>
</head>
<body>

<br> </br>
<br> </br>
<br> </br>
<br> </br>

<div class="container">

  <div style="text-align:center">
    <h2 style="font-family:Vivaldi; font-size:300%;"> Pišite  nam ... </h2>
    
  </div>
  
     
    </div>
    <div class="column">
      <form action="/action_page.php">
        <label for="fname">Ime</label>
        <input type="text" id="fname" name="firstname" placeholder="Vaše ime..">
        <label for="lname">Prezime</label>
        <input type="text" id="lname" name="lastname" placeholder="Vaše prezime..">
        <label for="country">E-mail</label>
        <input type="text" id="lname" name="lastname" placeholder="Vaš e-mail..">
        <label for="subject">Poruka</label>
        <textarea id="subject" name="subject" placeholder="Napiši poruku.." style="height:170px"></textarea>
        <input type="submit" value="Pošalji">
      </form>
    </div>
  </div>
</div>



<br> </br>

app/views/pages/druga.html.erb
<div class="row">
<div class="col-md-2">
  <img src="/slika23.jpg" style="width:120% ; height: 80%">
</div>
<div class="col-md-2">
  <img src="/slika28.jpg" style="width:120% ; height: 80%">
</div>
<div class="col-md-2">
  <img src="/slika30.jpg" style="width:120% ; height: 80%">
</div>
<div class="col-md-2">
  <img src="/slika22.jpg" style="width:120% ; height: 80%">
</div>
<div class="col-md-2">
  <img src="/slika31.jpg" style="width:120% ; height: 80%">
</div>
<div class="col-md-2">
  <img src="/slika24.jpg" style="width:120% ; height: 80%">
</div>
</div>

 
 <h1 style="font-family:Edwardian Script ITC; font-size:500%;"> O n a m a . . . </h1> 







<p style= "font-size:120%;"> Portal Wedding Day namijenjen je budućim mladencima, kao i svim pružateljima usluga za vjenčanja u Bosni i Hercegovini. Cilj nam je da mladencima olakšamo svu potrebnu organizaciju, a vendorima pružimo mogućnost aktivnog oglašavanja, osmislili smo funkcionalni i lijepo dizajniran web katalog kojem se svi mogu pridružiti. </p>

<p style= "font-size:120%;"> Želimo biti vaša inspiracija i zbog toga planirajte svoje vjenčanje s nama! Mi volimo kreativne stvari i otvoreni smo za sve vaše ideje i prijedloge i zato nas kontaktirajte vezano za bilo kakav upit. Inspiracije, novosti, priče, fotografije i putovanja samo su djelić našeg malog svijeta vjenčanja. </p>


<br/><br/><br/>
<center>
 <iframe width="860" height="515" src="https://www.youtube.com/embed/Wxy80QvnMwA" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe> 
</center>

<br> </br>

<br> </br> 





<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}

.column {
  float: left;
  width: 33.3%;
  margin-bottom: 16px;
  padding: 0 8px;
}

@media screen and (max-width: 650px) {
  .column {
    width: 100%;
    display: block;
  }
}

.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
}

.container {
  padding: 0 16px;
}

.container::after, .row::after {
  content: "";
  clear: both;
  display: table;
}

.title {
  color: grey;
}

.button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #8c8c8c;
  text-align: center;
  cursor: pointer;
  width: 100%;
}

.button:hover {
  background-color: #b3b3b3;
}
</style>
</head>
<body>

<br> </br>
<h2 style="font-family:Edwardian Script ITC; font-size:500%;"> Meet the team... </h2> 

<p></p>
<br>

<div class="row">
  <div class="column">
    <div class="card">
      <img src="/minana.jpg" alt="Amina" style="width:100%">
      <div class="container">
        <h2>Amina Jelešković</h2>
        <p class="title">CEO & Founder</p>
        <p> +38762366909 </p>
        <p>amina.jeleskovic@outlook.com</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <img src="/mima.jpg" alt="Mima" style="width:100%">
      <div class="container">
        <h2>Fatima Fejzić</h2>
        <p class="title">Art Director</p>
        <p> +38762971614</p>
        <p>fatima.fejzic@hotmail.com</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>
  <div class="column">
    <div class="card">
      <img src="/ahmija.jpg" alt="Ahmija" style="width:100%">
      <div class="container">
        <h2>Ahmija Gurdić</h2>
        <p class="title">Designer</p>
        <p> +38762633852</p>
        <p>ahmija.gurdic@hotmail.com</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/pages/landing_page.html.erb
<style>
* {box-sizing: border-box;}
body {font-family: Verdana, sans-serif;}
.mySlides {display: none;}
img {vertical-align: middle;}

/* Slideshow container */
.slideshow-container {
  max-width: 1000px;
  position: relative;
  margin: auto;
}

/* Caption text */
.text {
  color: #f2f2f2;
  font-size: 15px;
  padding: 8px 12px;
  position: absolute;
  bottom: 8px;
  width:100% ;
  text-align: center;
}

/* Number text (1/3 etc) */
.numbertext {
  color: #f2f2f2;
  font-size: 12px;
  padding: 8px 12px;
  position: absolute;
  top: 0;
}

/* The dots/bullets/indicators */
.dot {
  height: 15px;
  width: 15px;
  margin: 0 2px;
  background-color: #bbb;
  border-radius: 50% ;
  display: inline-block;
  transition: background-color 0.6s ease;
}

.active {
  background-color: #717171;
}

/* Fading animation */
.fade {
  -webkit-animation-name: fade;
  -webkit-animation-duration: 3.5s;
  animation-name: fade;
  animation-duration: 3.5s;
}

@-webkit-keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}

@keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}

/* On smaller screens, decrease text size */
@media only screen and (max-width: 300px) {
  .text {font-size: 11px}
}
</style>
</head>
<body>



<div class="slideshow-container">

<div class="mySlides fade">
  <img src="slika0.jpg" style="width:100%">
</div>

<div class="mySlides fade">
  <img src="slika8.jpg" style="width:100%">
</div>

<div class="mySlides fade">
  <img src="slika7.jpg" style="width:100%">
</div>

</div>
<br>

<div style="text-align:center">
  <span class="dot"></span> 
  <span class="dot"></span> 
  <span class="dot"></span> 
</div>

<script>
var slideIndex = 0;
showSlides();

function showSlides() {
    var i;
    var slides = document.getElementsByClassName("mySlides");
    var dots = document.getElementsByClassName("dot");
    for (i = 0; i < slides.length; i++) {
       slides[i].style.display = "none";  
    }
    slideIndex++;
    if (slideIndex > slides.length) {slideIndex = 1}    
    for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
    }
    slides[slideIndex-1].style.display = "block";  
    dots[slideIndex-1].className += " active";
    setTimeout(showSlides, 2000); // Change image every 2 seconds
}
</script>

</body>
</html> 

<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-8">
<center> <p style="font-family:Vivaldi; font-size:200%;"> U želji da mladencima olakšamo svu potrebnu organizaciju, a vendorima pružimo mogućnost aktivnog oglašavanja, osmislili smo funkcionalni i lijepo dizajniran web katalog kojem se svi mogu pridružiti. </p> </center>
  </div>

  <div class="col-md-2">
  </div>








</body> 




&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

<div class="row">
  <div class="col-md-2">
    <img src="/slika4.jpg" style="width:100%">
  </div>
  <div class="col-md-2">
    <img src="/slika65.jpg" style="width:100%">
  </div>
  <div class="col-md-2">
    <img src="/slika6.jpg" style="width:100%">
  </div>
  <div class="col-md-2">
    <img src="/slika27.jpg" style="width:100%">
  </div>
  <div class="col-md-2">
    <img src="/slika3.jpg" style="width:100%">
  </div>
  <div class="col-md-2">
    <img src="/slika11.jpg" style="width:100%">
  </div>
</div>





<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
    box-sizing: border-box;
}

body {
    background-color: #f1f1f1;
    padding: 20px;
    font-family: Arial;
}

/* Center website */
.main {
    max-width: 1000px;
    margin: auto;
}

h1 {
    font-size: 50px;
    word-break: break-all;
}

.row {
    margin: 8px -16px;
}

/* Add padding BETWEEN each column */
.row,
.row > .column {
    padding: 8px;
}

/* Create four equal columns that floats next to each other */
.column {
    float: left;
    width: 25%;
}

/* Clear floats after rows */ 
.row:after {
    content: "";
    display: table;
    clear: both;
}

/* Content */
.content {
    background-color: white;
    padding: 10px;
}

/* Responsive layout - makes a two column-layout instead of four columns */
@media screen and (max-width: 900px) {
    .column {
        width: 50%;
    }
}

/* Responsive layout - makes the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 600px) {
    .column {
        width: 100%;
    }
}
</style>
</head>
<body>

<!-- MAIN (Center website) -->
<div class="main">



<center> <h2 style="font-family:Edwardian Script ITC; font-size:500%;""> P o n u d a . . .  </h2>
<p></p>

<!-- Portfolio Gallery Grid -->
<div class="row">
  <div class="column">
    <div class="content">
      <img src="decorr.png" alt="Mountains" style="width:100%">
      <h3>Dekoracije</h3>
      <p> U bogatoj ponudi dekoracija za vjenčanje čekaju vas: </p>
      <p> pomponi, rozete, konfeti, dekoracije za svadbeni auto, baloni i još mnogo dekoracija i dodataka za vaš posebni dan. </p>
      
    
    </div>
  </div>
  <div class="column">
    <div class="content">
    <img src="/slika14.jpg" alt="Lights" style="width:100%">
      <h3>Pozivnice</h3>
      <p>Za vaše pozivnice će se pobrinuti: </p>
      <p> Hp Cards - Svijet čestitki i pozivnica; Megatrend; Digital Print; Pozivnice - Nerina cvjećare .</p>
    </div>
  </div>
  <div class="column">
    <div class="content">
    <img src="/slika13.jpg" alt="Nature" style="width:100%">
      <h3>Torta</h3>
      <p>Najukusnije i najljepše torte za vaše vjenčanje možete poručiti u: </p>
      <p> Slatičarna Palma, Slastičarna Dessert, Prodavaonica Torte i to. </p>
    </div>
  </div>
  <div class="column">
    <div class="content">
    <img src="/slika9.jpg" alt="Mountains" style="width:100%">
      <h3>Restorani i hoteli</h3>
      <p>Nudimo Vam jedne od najeksluzivnijih hotela i restorana u našem gradu: </p>
      <p>Hotel Hills,Hotel „Radon Plaza“;Hotel Hollywood; Restoran Robinzon  .</p>
    </div>
  </div>
<!-- END GRID -->
</div>



<!-- Portfolio Gallery Grid -->
<div class="row">
  <div class="column">
    <div class="content">
      <img src="slika36.jpg" alt="Mountains" style="width:100%">
      <h3>Prstenje</h3>
      <p> Nudimo vam neke od najboljih zlatarni u Bosni i Hercegovini: </p>
      <p> Zlatarna Dar </p>
      <p>Zlatara Dijamant </p>
      <p>Zlatara Saraj </p>
  
    </div>
  </div>
  <div class="column">
    <div class="content">
    <img src="/slika16.jpg" alt="Lights" style="width:100%">
      <h3>Vjenčanice</h3>
      <p>Buduće mlade zablistajte uz: </p>
      <p>Salon vjenčanica Hill`s </p>
      <p>Salon vjenčanica Diva </p>
      <p>Salon vjenčanica Graziosa Sposa </p>
    </div>
  </div>
  <div class="column">
    <div class="content">
    <img src="/slika1.jpg" alt="Nature" style="width:100%">
      <h3>Prvi ples</h3>
      <p> Za vježbanje i usavršavanje vašeg prvog plesa pobrinuti će se Plesni Klub Astorija.</p>
      <br> <br/>
      <br></br>
    </div>
  </div>
  <div class="column">
    <div class="content">
    <img src="/slika15.jpg" alt="Mountains" style="width:100%">
      <h3>Medeni mjesec</h3>
      <p>Nudimo vam 5 destinacija za medeni mjesec kojeg ćete prepričavati svojim unucima!  To su: Paris, Maldivi, Santorini, Cappadocia, Dubai .</p>
      <br> </br>
      </div>
  </div>
<!-- END GRID -->
</div>



<div class="content">
  <img src="/slika12.jpg" alt="Bear" style="width:100%">
  <h3>Vjenčanje iz snova</h3>
  <p>
  <p>Planiranje vjenčanja treba biti jednostavno i zabavno, a mi vam želimo pružiti sve potrebne alate i informacije da to i postignete.</p>
  <p> Svijet vjenčanja je poseban, a mi znamo nešto o tome :) </p>
</div>

<!-- END MAIN -->
</div>

</body>
</html>

app/views/pages/peta.html.erb
<h1 style="font-family:Edwardian Script ITC; font-size:400%;"> L o g i n . . . </h1> 




<br> </br>











<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}
form {border: 3px solid #f1f1f1;}

input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

button {
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
}

button:hover {
    opacity: 0.8;
}

.cancelbtn {
    width: auto;
    padding: 10px 18px;
    background-color: #f44336;
}

.imgcontainer {
    text-align: center;
    margin: 24px 0 12px 0;
}

img.avatar {
    width: 40%;
    border-radius: 50%;
}

.container {
    padding: 16px;
}

span.psw {
    float: right;
    padding-top: 16px;
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
    span.psw {
       display: block;
       float: none;
    }
    .cancelbtn {
       width: 100%;
    }
}
</style>
</head>
<body>



<form action="/action_page.php">
  <div class="imgcontainer">
    <img src="img_avatar2.png" alt="Avatar" class="avatar">
  </div>

  <div class="container">
    <label for="uname"><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="uname" required>

    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" required>
        
    <button type="submit">Login</button>
    <label>
      <input type="checkbox" checked="checked" name="remember"> Remember me
    </label>
  </div>

  <div class="container" style="background-color:#f1f1f1">
    <button type="button" class="cancelbtn">Cancel</button>
    <span class="psw">Forgot <a href="#">password?</a></span>
  </div>
</form>

</body>
</html> 


<br> </br> 